### ISSUE TITLE
Allow configuring channels to always prefix /bs say and /bs act messages with the caller's account

### ISSUE THREAD

**Issue by GLolol** [atheme/atheme#487]
On larger community with many ops, it is very easy for one op to start abusing BotServ with little or no accountability to who's doing so. Perhaps there could be a `prefixsay` channel option that `botserv/bottalk` registers, so that if enabled, messages going through `/bs say/act` are prefixed with the caller's account: `<bot> [user1] Announcement`

The only workaround I can see is to stop using BotServ entirely on the affected channels, as not everyone has snoop channel or modunload access. But that sort of ruins the point of configurable bots in the first place.

**Comment by kaniini** [comment]
One of the main reasons why this isn't implemented per se is because botserv SAY/ACT is kinda meant to be used for specific use-cases like NPC characters in IRC RP campaigns.

I think that at least, to that end, the functionality needs to be considered in terms of not ruining that use-case.

**Comment by GLolol** [comment]
I think the behaviour should be configurable as in `/cs set #channel prefixsay on|off`, so it'd be up to channel owners to set how they want BotServ to be used.

**Comment by kaniini** [comment]
Sure, this is just a note to not enable it unconditionally.

**Comment by MrBenC** [comment]
Perhaps another option (configurable perhaps) might be op or halfop (if halfops are supported) channel notices saying who ran the command?  Although, this would not function properly in channels where staying opped at all times is uncommon.  This would be in a similar vein of VERBOSE and VERBOSEOPS.

General channel notices would not really be preferred over prefixes (or suffixes) since this would generate two lines of output for all users in the channel on each invocation of /bs SAY and ACT.

Ben
