### ISSUE TITLE
OperServ flood protection issue

### ISSUE THREAD

**Issue by Arkadietz** [atheme/atheme#492]
Hello,

I have a suggestion here. Since we discussing the topic in #atheme. I believe and for many others services must ignore the users instead kline them. So this future will be more appropriate.

P.S And yes i knew the fact flood protection can be disabled.

I will wait for your response.

Best regards

**Comment by siniStar7boy** [comment]
I must've missed the discussion in #atheme, but I don't agree with this proposal..  

Currently, when a user floods services, services will inform them that they are flooding it and are being ignored for 30 seconds.  Any floods to services after the intial warning and ignore will result in a 10 minute KLINE/AKILL.  

(This seems logical on most networks, _at least to me.  Since I missed the discussion, if there are any points or arguments to be made, please feel free to post them._)

**Comment by kaniini** [comment]
For what it's worth, that code predates the real services ignore system being implemented.  It makes sense to just convert the AKILL to a services ignore.

**Comment by siniStar7boy** [comment]
Over a year with no relevant pro-points on changing this functionality.  (Closing)
