### ISSUE TITLE
SET MLOCK +J can't be set above 4 seconds

### ISSUE THREAD

**Issue by Doemela** [atheme/atheme#509]
If I do /cs set #Channel mlock +ntCJ-lk 60 I get
>-ChanServ- Invalid value 60 for mode +J.

When I do cs set #Channel mlock +ntCJ-lk 4 it works 
>-ChanServ- The MLOCK for #Channel has been set to +ntCJ-kl.

Using  atheme-services-7.2.6 InspIRCD 2.0.23
/mode #Channel +J 60 works

**Comment by grawity** [comment]
Yes, I think that's intentional.

**Comment by Doemela** [comment]
Why?

**Comment by dwfreed** [comment]
See 0152fb3b155aa26e39993148bfea4245a72b86e4, #380, and inspircd/inspircd#913

**Comment by Doemela** [comment]
>See 0152fb3, #380, and inspircd/inspircd#913

The limit is 60 seconds imposed on inspircd 2.2 not 4 seconds that was on inspircd 2.0 (where no limit exists) As for the max 4s limit as the hard upper-bound, it is up to the server administrator to decide what is a sensible upper bound. I think that 60 seconds is reasonable.

**Comment by dwfreed** [comment]
And on inspircd 2.2, as referenced in those links, the ircd tells atheme what its configured maximum is, and atheme will then allow you to MLOCK +J to that maximum.  Since you on 2.0, as you mentioned above, this does not happen, and atheme falls back to its default limit, which is supposed to be 5 seconds, but due to a logic error, it will only allow 4 seconds.

**Comment by aaronmdjones** [comment]
As noted above, you can solve this problem by upgrading InspIRCd to 2.2, which will tell services what your limit is.
