### ISSUE TITLE
ChanServ/INVITE: Support inviting other people

### ISSUE THREAD

**Issue by Zarthus** [atheme/atheme#568]
Adding an optional parameter to ChanServ/INVITE to support `INVITE <#channel> [nick/account]` would be really nice if you don't want to op up to /invite someone.

It also indirectly solves the weird error message you get when you try to do this - giving a `(20:12:38) -ChanServ- Channel #channel nickname is not registered.` (#567)

**Comment by siniStar7boy** [comment]
I believe many services packages behave this way _(as a means to prevent abuse)_ since the late 90's..  _(Mass-inviting via Services, invite-spam from bots/scripts utilizing services, etc.)_  I don't personally see the need or benefit to change the functionality itself, though #567 should be fixed.    

I suppose it could be made configurable in the configuration, however, if this functionality was implemented.    

Other thoughts?

**Comment by bonnedav** [comment]
Many you can make it IRCOP only?
You could have the config option like this:
EnableCSInviteOthers
With 3 options:
Yes 
No 
IRCOPS

**Comment by Zarthus** [comment]
Just send a notice `Zarthus has invited you to #channel` to avoid the anonymization; as most other commands do (like voicing someone), I don't see how this is any different from regular invite spam.

**Comment by Xenthys** [comment]
If this gets implemented, it could be great to avoid sending the invite in case the client is +R/+g per example. Otherwise, I also like this idea from both points of view (oper & user).

**Comment by alyx** [comment]
After some review, we feel this could open up too many vectors for potential services abuse and the negatives outweigh the positives.
