### ISSUE TITLE
Valid e-mail addresses rejected

### ISSUE THREAD

**Issue by jernejs** [atheme/atheme#572]
I tried registering my nickname with an e-mail address that contains `|` in it, but the address was rejected as invalid - it's not. All of these characters:

```
#$&'*+-./=?^_`{|}~
```

are valid in the local part of e-mail address without having to use quotes.

Edited by @aaronmdjones (markdown quoting of characters)

**Comment by ilbelkyr** [comment]
It seems we have the correct set (even referencing RFC2822) in validemail in libathemecore/function.c … except it's inside an `#if 0`. I'm not sure if there's any reason not to use that instead of the subset that's actually used, though. (Quoted local parts probably aren't worth supporting, especially considering that'd allow for spaces which would mess up a bunch of our assumptions. I believe the lack of support for domain literals is a feature, not a bug.)

**Comment by ilbelkyr** [comment]
(I'll probably change it to the RFC set unless someone knows why we don't already use it.)

**Comment by aaronmdjones** [comment]
I don't see why we can't uncomment that and use the full set as long as we *ensure* that it is never passed to a shell command line (which will interpret `|` specially) (e.g. the invocation of the local MTA). This means executing the MTA directly instead of via a shell, and we should put a prominent warning in the commit message and the changelog that any custom scripts being used as an MTA command should be audited before pulling this change.

**Comment by aaronmdjones** [comment]
After a review of `sendemail` in `libathemecore/function.c` it seems as though the shell will not be used (unless the user specifies a shellscript as MTA command, but that won't matter for `|`). `NEWS.md` even mentions the lack of shell now (a while ago) which is good.

We still need the prominent warning for anyone using a shell script as an MTA command as they may be executing other commands with the e-mail address as an argument without quoting it.
