### ISSUE TITLE
When registering the response contains the password as plain text.

### ISSUE THREAD

**Issue by Busti** [atheme/atheme#577]
When messaging NickServ using `/msg NickServ register` the password is initially obfuscated in the send message.  
That obfuscation is immediately broken however since NickServ responds with:
`<user> is now registered to <email>, with the password <plaintext-password>`

This can be rather dangerous since it is openly visible in the buffer until it is cleared, and someone with ill intents could probably read the password and username combination.  
And since many people carelessly use the same username and password combination throughout many different services the read password could be used to log into e.g. amazon.

Thanks to @lol768 for finding the responsible line of code:
https://github.com/atheme/atheme/blob/4fd9583b7b8498fb5379b2c07ec4de50f877d85e/modules/nickserv/register.c#L230

**Comment by euank** [comment]
> the password is initially obfuscated in the send message

Mind explaining what you mean there? If you're referring to your client's input box, well, that's entirely irc client dependent and unrelated to atheme in any way.

**Comment by aaronmdjones** [comment]
> If you're referring to your client's input box

They are. WeeChat's implementation replaces the characters with `*` for display (and changes them to `*` in the history too, so you can't hit the up arrow and modify the previously sent message to e.g. `/msg nefarious_actor ****` to obtain the password either). It does this for register and identify at least, but as far as I know it can only act on input, not received text, so as far as I know it can't be extended to obfuscate the password returned by services in the offending message.

Given that some clients obfuscate the password as it is entered, NOT returning the password to the user would be detrimental if the user ever made a typo (they would not know). However, given that things like `sendpass` exist, I would be okay with removing the password from the registration success message.

**Comment by siniStar7boy** [comment]
> This can be rather dangerous since it is openly visible in the buffer until it is cleared, and someone with ill intents could probably read the password and username combination.
And since many people carelessly use the same username and password combination throughout many different services the read password could be used to log into e.g. amazon.    

This is not an atheme security issue.  This is _basic_ computer security.  If you are going to walk away from your computer, especially in public: lock it.

**Comment by euank** [comment]
Note as well that if you care about security you should be using SASL / certificate auth, which renders any concern of typing passwords into irc moot.

**Comment by ilbelkyr** [comment]
Other software does often try to avoid displaying passwords in an unobscured form. I don't think this is a significant issue here, especially as it only comes up once (during registration); as for changing this, I pretty much agree with @aaronmdjones on this.

**Comment by siniStar7boy** [comment]
> Given that some clients obfuscate the password as it is entered, NOT returning the password to the user would be detrimental if the user ever made a typo (they would not know).    

I agree.  (Yes, they can use SENDPASS to fix this - but the whole scenario could have been avoided with current functionality.)

> I would be okay with removing the password from the registration success message.    

I feel the change is not necessary and further opens the above scenario to becoming more common.  In the time that atheme has _done this_ as it is now; I am unaware of _any_ networks running atheme _(including the largest)_ complaining about or removing the functionality from their forks of it.    

> Other software does often try to avoid displaying passwords in an unobscured form. I don't think this is a significant issue here, especially as it only comes up once (during registration); as for changing this, I pretty much agree with @aaronmdjones on this.    

While a lot of software and services try to avoid displaying the passwords in an unobscured form; some do during setup/registration and password resets for the very same reason already pointed out. _(possible typo's)_    

I will re-open the issue so that it can be discussed further, but unless a _compelling_ reason is provided; I will likely close it again.

**Comment by maxteufel** [comment]
> This is not an atheme security issue. This is basic computer security. If you are going to walk away from your computer, especially in public: lock it.

It is. Secure software should not leave the security part in the hands of the user. Users who are less knowledgeable about security **will not** know how to act in the right way. Besides from this showing up in the client's current output, this could also be logged to some text file in plain text (again, potentially **without** the user knowing that it is there) which is not a secure place for passwords.

If we want to avoid typos when setting the password we could think about introducing a new `VERIFY` method so you have to type passwords twice.

**Comment by lol768** [comment]
:+1: for leaving this open. One of the major reasons `<input type="password">` exists on the web is to prevent "shoulder surfing". On the web, the typo problem is usually fixed by having a confirm input field or alternatively a switch which can be used to temporarily unmask the password input.

As a further example, you don't see an ATM display your PIN on screen once you confirm it. The issue here isn't even related to locking or not locking the computer - it's visible to an observer close by if you happen to register in public.
