### ISSUE TITLE
Remove Chanserv from channel

### ISSUE THREAD

**Issue by pwpx2** [atheme/atheme#620]
If i am the Oper of the network how could i remove ChanServ from a channel if i don't have access to it and registering under my name ?
The owner of the channel and chanserv hasn't been around in days and i need access to chanserv to make some changes on the channel

**Comment by ilbelkyr** [comment]
Taking actions as network staff generally requires you to use different commands to indicate you're using your authority as network staff (rather than channel staff). You might be looking for the `FFLAGS`, `FTRANSFER`, or `FDROP` commands.

These are separate from the normal commands in Atheme by design.
