### ISSUE TITLE
misc/httpd: unload doesn't close listening socket

### ISSUE THREAD

**Issue by dwfreed** [atheme/atheme#628]
Unloading misc/httpd calls connection_close_soon_children, which marks the listener as dead, along with all of the connections created from it that still exist.  However, this doesn't actually close the sockets, leaving them to linger until Atheme exits.  For connected sockets, this probably isn't an issue, because the client will close its end, and eventually the OS will clean up the connection information (though the file descriptor will still linger).  For the listening socket, however, it'll stay listening forever, but attempting to connect to it will hang because accept() never gets called.

**Comment by aaronmdjones** [comment]
Can you test if commit 5e51a5af2b052e5e054641da5357d321e3dc8a0c resolves this issue?

**Comment by dwfreed** [comment]
I modified it to work with 7.2 (mostly just switching `struct connection` back to `connection_t`), and it works there, so it should work on master as well.

**Comment by aaronmdjones** [comment]
Thanks.

I'll leave this open for a bit, because I want to dive deeper into the connection code; some of it looks sub-optimal, and I want to be sure that there are no lingering crash bugs from this change.

I'll also throw it on my testnet under Valgrind before I put this on release/7.2 and master. That will have to wait until Monday.
