### ISSUE TITLE
null dereference

### ISSUE THREAD

**Issue by 360CodeSafe** [atheme/atheme#629]
atheme/libathemecore/culture.c  line 222

if line 221 return null pointer ,and null pointer value stored to 'lang' , then access to field 'flags' results in a dereference of a null pointer(loaded from variable 'lang')

**Comment by aaronmdjones** [comment]
False positive. The only way `language_add()` will return `NULL` is if you give it a `NULL` `name` or if the `name` is `"default"`, both of which are checked for before calling it.

**Comment by 360CodeSafe** [comment]
why name could not equal NULL?

**Comment by aaronmdjones** [comment]
`modules/backend/corestorage.c`:

```
language = db_read_word(db);        // <<----
mu = myuser_add_id(uid, name, pass, email, flags);
mu->registered = reg;
mu->lastlogin = login;
if (language)        // <<----
	mu->language = language_add(language);
```

Note that the code does not dereference `mu->language` after, so a `NULL` return is fine.



`modules/backend/flatfile.c`:

```
language = strtok(NULL, " ");        // <<----
mu = myuser_add(muname, mupass, muemail, atol(flagstr));
mu->registered = registered;
mu->lastlogin = lastlogin;
// [...]
if (language != NULL)        // <<----
	mu->language = language_add(language);
```

Same here; a `NULL` return is fine.



`libathemecore/culture.c`:

```
lang = language_add("en");
lang->flags |= LANG_VALID;
```

This is fine; it will never return `NULL`.

```
dir = opendir(LOCALEDIR);
if (dir != NULL)        // <<----
{
	while ((ent = readdir(dir)) != NULL)        // <<----
	{
		if (ent->d_name[0] != '.' &&
				strcmp(ent->d_name, "all_languages") &&
				strcmp(ent->d_name, "locale.alias") &&
				strcmp(ent->d_name, "default"))        // <<----
		{
			lang = language_add(ent->d_name);        // <<----
			lang->flags |= LANG_VALID;
		}
	}
	closedir(dir);
}
```

`ent->d_name` is the name of the file in the directory entry; filenames cannot be `NULL`. Even if the OS is really broken enough to give an application a `NULL` filename, the code would explode on `if (ent->d_name[0] != '.')`, rather than in `language_add()`.

**Comment by 360CodeSafe** [comment]
understand，thank you  very much
