### ISSUE TITLE
SeenServ

### ISSUE THREAD

**Issue by polat199** [atheme/atheme#666]
i would like you to tell me how to make seenserv for atheme services ?

**Comment by alyx** [comment]
Hey, thanks for your interest in extending Atheme functionality! :smile: 

Currently, due to the privacy concerns involved, SeenServ is not something we're planning on adding to core Atheme functionality, but you're more than welcome to build your own on top of our platform — we currently have both a C API and a Perl API available, although you'll need to dig into the code right now as we're still getting a shiny documentation website put together.

If you're comfortable with C, some good starting points would probably be: [atheme-contrib-modules/ircd_loveserv.c](https://github.com/atheme/atheme-contrib-modules/blob/master/ircd_loveserv.c), which demos how you can build a new service bot and assign commands to it; as well as [atheme/modules/nickserv/info.c](https://github.com/atheme/atheme/blob/release/7.2/modules/nickserv/info.c) which shows off how you can get some last seen information for _registered_ users!

If you're more comfortable with Perl, you can check out [atheme/modules/scripting/perl/examples/catserv.pl](https://github.com/atheme/atheme/blob/release/7.2/modules/scripting/perl/examples/catserv.pl), which demos how to create a new service and assign a command using our Perl interface — I should note though that internally at Atheme, we don't use the Perl interface too much anymore, so I can't perfectly promise that full functionality is present through the Perl scripting interface.

We can't write the whole thing for you, but we're always happy to talk with a fellow developer about what bits of Atheme they're hacking on. I'm going to go ahead and close this issue since there's not really a bug involved, but feel free to comment or visit us on irc.freenode.net/#atheme if you have any more questions about building on top of Atheme!
