### ISSUE TITLE
saslserv/ecdsa-nist256p-challenge misuses openssl's ECDSA_verify() by not hashing the challenge

### ISSUE THREAD

**Issue by ProgVal** [atheme/atheme#684]
Hi,

I was recently made aware that Atheme supports ECDSA auth; so I started working on patching [Limnoria](https://github.com/ProgVal/Limnoria)'s implementation to work with Atheme.
While doing so, I noticed that Atheme requires the client to sign the challenge without hashing it.

---

From the OpenSSL doc:

```
 int ECDSA_sign(int type, const unsigned char *dgst, int dgstlen,
                unsigned char *sig, unsigned int *siglen, EC_KEY *eckey);

 int ECDSA_verify(int type, const unsigned char *dgst, int dgstlen,
                  const unsigned char *sig, int siglen, EC_KEY *eckey);
```

> ECDSA_sign() computes a digital signature of the dgstlen bytes hash value dgst using the private EC key eckey.
> ECDSA_verify() verifies that the signature in sig of size siglen is a valid ECDSA signature of the hash value dgst of size dgstlen using the public key eckey.

However, Atheme does not hash the value before passing it to `ECDSA_verify`.

[ecdsatool/libecdsaauth](https://github.com/kaniini/ecdsatool/) has the same issue with `ECDSA_verify` (the code is the same as atheme, minus the plumbing) as well as `ECDSA_sign`.

This shouldn't be too much of an issue for Atheme as it controls the size of the challenge; but it is very hard to handle for clients, with even thin abstractions over OpenSSL, as they all expect a hash algorithm to work.

For example, here is how I had to patch Limnoria to make it work with Atheme (and then, it only works with Atheme):

```diff
diff --git a/src/irclib.py b/src/irclib.py
index af0de223..a6cc013f 100644
--- a/src/irclib.py
+++ b/src/irclib.py
@@ -42,7 +42,7 @@ class crypto:
             import load_pem_private_key
         from cryptography.hazmat.backends import default_backend
         from cryptography.hazmat.primitives.asymmetric.ec import ECDSA, SECP256R1
-        from cryptography.hazmat.primitives.hashes import SHA256
+        from cryptography.hazmat.primitives.asymmetric.utils import Prehashed
 except ImportError:
     crypto = None
 
@@ -1178,12 +1178,25 @@ def doAuthenticateEcdsa(self, string):
         if string == b'':
             self.sendSaslString(self.sasl_username.encode('utf-8'))
             return
+
+        # Build a Prehashed subclass to trick python-cryptography into
+        # not hashing the string.
+        class IdentityHash(crypto.Prehashed):
+            def __init__(self):
+                pass
+
+            @property
+            def _algorithm(self):
+                obj = object()
+                obj.digest_size = len(string)
+                return obj
+
         try:
             with open(self.sasl_ecdsa_key, 'rb') as fd:
                 private_key = crypto.load_pem_private_key(
                     fd.read(),password=None, backend=crypto.default_backend())
             authstring = private_key.sign(
-                string, crypto.ECDSA(crypto.SHA256()))
+                string, crypto.ECDSA(IdentityHash()))
             self.sendSaslString(authstring)
         except (OSError, ValueError):
             self.sendMsg(ircmsgs.IrcMsg(command='AUTHENTICATE',
```

and it only works because I abused Python's dynamic typing.

Additionally, I do not know if OpenSSL is hardened against arbitrary strings of arbitrary length used as value for `dgst`, which is possibly a security issue for clients.

---

As Atheme and Limnoria are, to the best of my knowledge, the only server-side and client-side implementations to support ecdsa, I think we can and should discuss how to change the current protocol/specification.

So far Limnoria used sha1 as it's the default hash of its cryptographic library; but I don't see any issue with moving to sha256 as apparently no one uses ecdsa it already.

**Comment by aaronmdjones** [comment]
Hello.

As you point out, Atheme generates a cryptographically-secure pseudorandom challenge of the appropriate size to pass directly to the client so that it can sign it. This uses the `prime256v1` (`NIST P-256`) curve, so it should be 256 bits (32 bytes) large.

This is indeed what you would get from running `SHA256()` over a challenge (of any size), but the decision was made when this mechanism was created a very long time ago that it's faster to just generate 32 bytes and sign them directly instead, skipping any hashing.

If you are concerned about passing a string of unknown length to your signing function, simply ensure that it is always 32 bytes first.

This mechanism is already in widespread use. As far as clients, at least Irssi (via a script [1]), WeeChat [2], and KICL [3] support it (in addition to Limnoria). freenode recommends it [4] (or `EXTERNAL`) for connecting via the Tor hidden service (which does not allow password-based mechanisms because bruteforcing cannot be dealt with -- all connections come from localhost). Changing it at this point would break those.

If you are looking to support a new SASL mechanism that has been through standardisation, may I suggest SASL SCRAM (RFC 5802). This is also being recommended by the IRCv3 Working Group, and has some support already matured in several bots and clients [5]. Atheme supports it too [6].

If you are looking to remain with a public-key cryptography based mechanism, so that you can set a random password on an account, promptly forget it, and then, for good measure, set the NickServ `NOPASSWORD` flag too, I have already created a new SASL mechanism in Atheme master called `ECDH-X25519-CHALLENGE`, which is intended to eventually replace `ECDSA-NIST256P-CHALLENGE`. A design rationale and implementation instructions are available in the comment block at the very beginning of the file [7], and a tool has been provided for interoperability testing [8]. I can also provide access to my Atheme testnet on request; this feature is available there. Many libraries can do Curve25519 key agreement if you wish to pursue this path, including e.g. libsodium, which has many Python bindings.

[1] https://github.com/atheme/atheme/blob/master/contrib/cap_sasl.pl
[2] https://weechat.org/files/doc/stable/weechat_user.en.html#irc_sasl_ecdsa_nist256p_challenge
[3] https://kitteh-irc-client-library.readthedocs.io/en/documentation/advanced/ecdsa/
[4] https://freenode.net/kb/answer/chat#accessing-freenode-via-tor
[5] https://ircv3.net/docs/sasl-mechs
[6] https://github.com/atheme/atheme/blob/master/doc/SASL-SCRAM-SHA
[7] https://github.com/atheme/atheme/blob/master/modules/saslserv/ecdh-x25519-challenge.c#L7-L129
[8] https://github.com/atheme/atheme/blob/master/NEWS.md#sasl
