### ISSUE TITLE
i have a problem

### ISSUE THREAD

**Issue by priemtjhh** [atheme/atheme#689]
![Schermafdruk van 2020-02-06 20-52-20](https://user-images.githubusercontent.com/60756355/73973693-5a8b8f00-4923-11ea-887a-4beacd4dedca.png)

i run the latest ubuntu on Vm 
and i followed a guide to configurate this
but it always shows errors
can someone help me out ?

**Comment by MikkelDK** [comment]
Did you edited on atheme.conf ?

**Comment by alyx** [comment]
Hey there!

Since we haven't heard back from you in a few months, I'm going to go ahead and close this issue. 

If you continue having issues setting up Atheme, feel free to reach back out! You can touch base with us here on the issue tracker or on IRC at irc.freenode.net in #atheme :) I personally recommend the IRC channel as it's a much better likelihood of getting a reasonably swift response.

Thanks and thanks for using Atheme!
