### ISSUE TITLE
password change

### ISSUE THREAD

**Issue by ViniProTheBro** [atheme/atheme#717]
idea to make it so a password change requires email verification.

**Comment by aaronmdjones** [comment]
This would be of extremely limited use, and no security benefit, because someone who's managed to login to your services account, or acquire access to a connection already logged into your services account (such as a malicious bouncer operator), can just change your account's e-mail address first with the NickServ `SET EMAIL` command.

**Comment by aaronmdjones** [comment]
Closing.
