### ISSUE TITLE
language does not change

### ISSUE THREAD

**Issue by netkrd** [atheme/atheme#768]
services language does not change

Valid languages are: en cy da de tr fr es ru

[00:42:26] -​NickServ​- Valid languages are: en cy da de tr fr es ru

/Ns set language de 

[00:43:19] -​NickServ​- The language for test has been changed to de.

/Ns Help
But I'm changing english again

[00:44:41] -​NickServ​- NickServ allows users to 'register' a nickname, and stop
others from using that nick. NickServ allows the owner of a

**Comment by netkrd** [comment]
Atheme git version and atheme-services-v7.2.11.tar.xz po files different

**Comment by dwfreed** [comment]
That string lacks a translation:

(release/7.2)
https://github.com/atheme/atheme/blob/859a6b0e944f3c59e1f26e97bb4ee886255c12f7/po/de.po#L5345-L5352

(master)
https://github.com/atheme/atheme/blob/4f925d78b375a817fc371a4bce4a21579f79d05c/po/de.po#L52-L59

When there is no translation, gettext falls back to using the msgid, which is in English.  You can help by contributing translations.

The PO files are going to be different, because they depend on what translatable strings are in the code, and that's usually going to change between released versions and current development.

**Comment by aaronmdjones** [comment]
As @dwfreed points out, some of our source code strings do not have translations currently. Getting the master branch translated is on our TODO, and we are actively accepting translations for the `help/` directory. We will not be backporting translations from master to 7.2 because the set of translatable strings are different.
